# Generated by Django 4.1.2 on 2022-10-27 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='제품 이름')),
                ('description', models.TextField(null=True, verbose_name='제품 설명')),
                ('price', models.IntegerField(verbose_name='제품 가격')),
            ],
            options={
                'verbose_name': '제품',
                'verbose_name_plural': '제품 정보',
                'db_table': 'Product',
            },
        ),
    ]
