# Generated by Django 4.1.2 on 2022-10-27 14:19

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Product', '0001_initial'),
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=50, verbose_name='수령 고객 이름')),
                ('recipient_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='SK', verbose_name='수령 고객 전화번호')),
                ('ordered_at', models.DateTimeField(auto_now_add=True, verbose_name='주문 날짜')),
                ('address', models.CharField(max_length=50, verbose_name='주소')),
                ('quantity', models.IntegerField(verbose_name='제품 수량')),
                ('status', models.PositiveIntegerField(choices=[(0, '결제 완료'), (1, '배송준비중'), (2, '배송중'), (3, '배송완료')], default=0, verbose_name='주문 상태')),
                ('orderer_id', models.ForeignKey(db_column='orderer_id', on_delete=django.db.models.deletion.CASCADE, to='Customer.customer', verbose_name='주문 고객 정보')),
                ('product_id', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='Product.product', verbose_name='제품 정보')),
            ],
            options={
                'verbose_name': '주문',
                'verbose_name_plural': '주문 정보',
                'db_table': 'Order',
            },
        ),
    ]
