# Generated by Django 4.1.2 on 2022-10-27 14:19

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='이메일')),
                ('customer_name', models.CharField(max_length=50, verbose_name='고객 이름')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='SK', unique=True, verbose_name='전화번호')),
            ],
            options={
                'verbose_name': '고객',
                'verbose_name_plural': '고객 정보',
                'db_table': 'Customer',
            },
        ),
    ]
